from fpdf import FPDF
from pathlib import Path
from ..core.models import Investigation

class HeartBleedPDF(FPDF):
    def header(self):
        from .. import __version__
        self.set_font('Arial', 'B', 15)
        self.set_text_color(192, 57, 43) # HeartBleed Red
        self.cell(0, 10, f'HEARTBLEED OSINT REPORT - v{__version__}', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Generated by HeartBleed - Page ' + str(self.page_no()), 0, 0, 'C')

def export_to_pdf(investigation: Investigation, output_path: Path):
    """
    Generates a professional PDF report for an investigation using FPDF v1.
    """
    pdf = HeartBleedPDF()
    pdf.add_page()
    
    # 1. Summary Header
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Investigation Summary: " + str(investigation.input_value), 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, "Target Type: " + str(investigation.input_type.value), 0, 1)
    pdf.cell(0, 8, "Timestamp: " + investigation.timestamp.strftime('%Y-%m-%d %H:%M:%S'), 0, 1)
    pdf.cell(0, 8, "Profiles Found: " + str(len(investigation.profiles)), 0, 1)
    pdf.ln(5)

    # 2. Persona Profile
    if investigation.persona_profile:
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 10, "Auto-Analyzed Persona Profile", 0, 1, 'L', 1)
        pdf.set_font('Arial', '', 10)
        for cat, kws in investigation.persona_profile.items():
            if kws:
                pdf.multi_cell(0, 8, str(cat) + ": " + ", ".join(kws), 0)
        pdf.ln(5)

    # 3. Discovered Accounts
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, "Discovered Profiles & Correlations", 0, 1)
    
    # Table Header
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(40, 10, "Platform", 1, 0, 'C', 1)
    pdf.cell(50, 10, "Username", 1, 0, 'C', 1)
    pdf.cell(20, 10, "Score", 1, 0, 'C', 1)
    pdf.cell(80, 10, "URL", 1, 1, 'C', 1)
    
    # Table Content
    pdf.set_font('Arial', '', 9)
    for res in investigation.correlations:
        p = res.target_profile
        pdf.cell(40, 10, str(p.platform), 1)
        pdf.cell(50, 10, str(p.username), 1)
        pdf.cell(20, 10, str(res.score), 1, 0, 'C')
        # Use a smaller font for the URL if it's long
        url_font_size = 9 if len(p.url) < 40 else 7
        pdf.set_font('Arial', '', url_font_size)
        pdf.cell(80, 10, str(p.url), 1, 1)
        pdf.set_font('Arial', '', 9)

    # 4. Investigative Resources
    if investigation.dorks:
        pdf.ln(10)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 10, "Investigative Search Links (Dorks)", 0, 1)
        pdf.set_font('Arial', '', 8)
        pdf.set_text_color(52, 152, 219) # Link Blue
        for d in investigation.dorks:
            pdf.write(8, "* " + str(d['name']) + ": " + str(d['url']))
            pdf.ln(8)

    pdf.output(str(output_path), 'F')
    return output_path
